In [1]:
i = 1
i

In [2]:
i

In [3]:
c = 2
c

In [4]:
import numpy as np

In [5]:
normal_list = range(10000)
normal_list
%timeit [i**2 for i in normal_list]

3 ms ± 22.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
np_list = np.arange(10000)
%timeit np_list**2

7.52 µs ± 212 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [8]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [9]:
stock_cnt = 200
view_days = 504
stock_day_change = np.random.standard_normal((stock_cnt, view_days))
print(stock_day_change.shape)

(200, 504)


In [10]:
print(stock_day_change[0:2, 0:5])
stock_day_change[0:2, 0:5].astype(int)

[[ 1.16271461  0.46731818  1.00295118 -0.02125313 -0.2623814 ]
 [ 1.34272826  0.77147734 -0.61149497  1.63538391 -0.11709103]]


array([[1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0]])

In [11]:
mask = stock_day_change[0:2, 0:5] > 0.5
mask

array([[ True, False,  True, False, False],
       [ True,  True, False,  True, False]])

In [12]:
stock_day_change_four = stock_day_change[0:4, 0:4]
stock_day_change_four

array([[ 1.16271461,  0.46731818,  1.00295118, -0.02125313],
       [ 1.34272826,  0.77147734, -0.61149497,  1.63538391],
       [-0.35951102,  1.01968789,  0.70970749,  0.51248405],
       [ 2.42090616,  1.76845445,  0.42956707,  0.43741617]])

In [13]:
np.max(stock_day_change_four, axis = 1)

array([1.16271461, 1.63538391, 1.01968789, 2.42090616])

In [14]:
help(np.std)

Help on function std in module numpy:

std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)
    Compute the standard deviation along the specified axis.
    
    Returns the standard deviation, a measure of the spread of a distribution,
    of the array elements. The standard deviation is computed for the
    flattened array by default, otherwise over the specified axis.
    
    Parameters
    ----------
    a : array_like
        Calculate the standard deviation of these values.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the standard deviation is computed. The
        default is to compute the standard deviation of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a standard deviation is performed over
        multiple axes, instead of a single axis or all the axes as before.
    dtype : dtype, optional
        Type to use in computing the standard deviation. For arrays of
       

In [15]:
help(np.mean)

Help on function mean in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For integer inputs,

In [16]:
stock_day_change_four
print(stock_day_change_four)
print(np.mean(stock_day_change_four, axis = 1))
print((stock_day_change_four[0][0] + stock_day_change_four[0][1] + stock_day_change_four[0][2] + stock_day_change_four[0][3]) / 4)

[[ 1.16271461  0.46731818  1.00295118 -0.02125313]
 [ 1.34272826  0.77147734 -0.61149497  1.63538391]
 [-0.35951102  1.01968789  0.70970749  0.51248405]
 [ 2.42090616  1.76845445  0.42956707  0.43741617]]
[0.65293271 0.78452364 0.47059211 1.26408596]
0.6529327134951878


In [22]:
#help(np.random.normal)
a_investor = np.random.normal(loc=100, scale = 50, size = (100, 1))
b_investor = np.random.normal(loc=100, scale = 20, size = (100, 1))

In [27]:
print('a.mean = {}, a.std = {}, a.var = {}'.format(a_investor.mean(), a_investor.std(), a_investor.var()))
print('b.mean = {}, b.std = {}, b.var = {}'.format(b_investor.mean(), b_investor.std(), b_investor.var()))


a.mean = 102.21229703832876, a.std = 55.22561878916751, a.var = 3049.8689706464515
b.mean = 98.71754446523443, b.std = 19.479708201742042, b.var = 379.45903162501617


In [30]:
a_mean = a_investor.mean()
a_std = a_investor.std()

In [35]:
import scipy.stats as scs

In [38]:
stock_mean = stock_day_change[0].mean()
stock_std = stock_day_change[0].std()
print('stock mean = {}, stock std = {}'.format(stock_mean, stock_std))

stock mean = -0.016849908896911892, stock std = 0.9804810164046804


In [50]:
np.save('./stock_day_change.npy', stock_day_change)

In [52]:
from abc import ABCMeta, abstractmethod
import six